server:
port: 7879
spring:
  application:
    name:  configclient
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
    config:
      server:
        git:
          uri: https://github.com/Monologuter/springcloudconfig.git
          basedir: /Users/macbookpro/soft/IdeaProjects/springcloud_parent/configServer/src/main/resources/localconfig
          default-label: prod
